
SET QUOTED_IDENTIFIER ON;

CREATE TABLE dbo.SKU
(
 ID INT IDENTITY(1,1) NOT NULL,
 Code AS ('s' + CAST([ID] AS VARCHAR(50))) PERSISTED,
 Name VARCHAR(255) NOT NULL,
 CONSTRAINT PK_SKU
 PRIMARY KEY(ID),
 CONSTRAINT UK_SKU_Code
 UNIQUE(Code)
);

CREATE TABLE dbo.Family
(
  ID INT IDENTITY(1,1) NOT NULL,
  SurName VARCHAR(50) NOT NULL,
  BudgetValue numeric,
  CONSTRAINT PK_Family
  PRIMARY KEY(ID),
 );


CREATE TABLE dbo.Basket
(
  ID INT IDENTITY(1,1) NOT NULL,
  ID_SKU INT NOT NULL,
  ID_Family INT NOT NULL,
  Quantity INT NOT NULL,
  Value NUMERIC NOT NULL,
  PurchaseDate DATE NOT NULL DEFAULT GETDATE(),
  DiscountValue NUMERIC,

  CONSTRAINT FK_BASKET_ID_SKU_SKU
  FOREIGN KEY(ID_SKU)
  REFERENCES dbo.SKU(ID),
  CONSTRAINT FK_BASKET_ID_Family_Family
  FOREIGN KEY(ID_Family)
  REFERENCES dbo.Family(ID),
  CONSTRAINT CK_BASKET_QuantityValue
  CHECK(Quantity>0 AND Value>0)
 );